apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-correlator
  namespace: netops-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-correlator
  template:
    metadata:
      labels:
        app: core-correlator
    spec:
      nodeSelector:
        kubernetes.io/hostname: r450
      initContainers:
        - name: wait-kafka
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-ec"]
          args:
            - |
              until nc -z netops-kafka.netops-core.svc.cluster.local 9092; do
                echo "waiting for kafka netops-kafka.netops-core.svc.cluster.local:9092"
                sleep 3
              done
      containers:
        - name: core-correlator
          image: netops-core-app:0.1
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "core.correlator.main"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: netops-kafka.netops-core.svc.cluster.local:9092
            - name: KAFKA_TOPIC_RAW
              value: netops.facts.raw.v1
            - name: KAFKA_TOPIC_ALERTS
              value: netops.alerts.v1
            - name: CORRELATOR_GROUP_ID
              value: core-correlator-v2
            - name: KAFKA_AUTO_OFFSET_RESET
              value: latest
            - name: RULE_DENY_WINDOW_SEC
              value: "60"
            - name: RULE_DENY_THRESHOLD
              value: "200"
            - name: RULE_BYTES_WINDOW_SEC
              value: "300"
            - name: RULE_BYTES_THRESHOLD
              value: "100000000"
            - name: RULE_ALERT_COOLDOWN_SEC
              value: "300"
