apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-alerts-sink
  namespace: netops-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-alerts-sink
  template:
    metadata:
      labels:
        app: core-alerts-sink
    spec:
      nodeSelector:
        kubernetes.io/hostname: r450
      initContainers:
        - name: wait-kafka
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-ec"]
          args:
            - |
              until nc -z netops-kafka.netops-core.svc.cluster.local 9092; do
                echo "waiting for kafka netops-kafka.netops-core.svc.cluster.local:9092"
                sleep 3
              done
      containers:
        - name: core-alerts-sink
          image: netops-core-app:0.1
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "core.alerts_sink.main"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: netops-kafka.netops-core.svc.cluster.local:9092
            - name: KAFKA_TOPIC_ALERTS
              value: netops.alerts.v1
            - name: KAFKA_TOPIC_DLQ
              value: netops.dlq.v1
            - name: ALERTS_SINK_GROUP_ID
              value: core-alerts-sink-v1
            - name: KAFKA_AUTO_OFFSET_RESET
              value: latest
            - name: ALERTS_OUTPUT_DIR
              value: /data/netops-runtime/alerts
            - name: ALERTS_SINK_LOG_INTERVAL_SEC
              value: "30"
          volumeMounts:
            - name: netops-runtime
              mountPath: /data/netops-runtime
      volumes:
        - name: netops-runtime
          hostPath:
            path: /data/netops-runtime
            type: DirectoryOrCreate
