apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: netops-core
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: netops-core
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      nodeSelector:
        kubernetes.io/hostname: r450
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          env:
            - name: CLICKHOUSE_DB
              value: netops
            - name: CLICKHOUSE_USER
              value: netops
            - name: CLICKHOUSE_PASSWORD
              value: netops123
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi
